name: Sync Blog and Deploy

on:
  push:
    branches:
      - main
    paths:
      - 'package.json'
      - 'scripts/sdk-versions.json'

jobs:
  sync-blog:
    uses: ./.github/workflows/sync-blog.yml  # Reuse the sync-blog job

  build-and-deploy:
    runs-on: ubuntu-latest
    needs: sync-blog  # Wait for blog sync to finish

    steps:
      - name: Checkout portfolio repo
        uses: actions/checkout@v3

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Build
        run: npm run build

      - name: List dist folder before deploy
        run: ls -R dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
