name: Sync Blog and Deploy

on:
  push:
    branches:
      - main
    paths:
      - 'package.json'                # when app version changes
      - 'scripts/sdk-versions.json'   # when blog version config changes

jobs:
  call-sync-blog:
    uses: ./.github/workflows/sync-blog.yml

  build-and-deploy:
    runs-on: ubuntu-latest
    needs: call-sync-blog

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install deps
        uses: bahmutov/npm-install@v1

      - name: Build
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
