# name: Sync Blog Content

# on:
#   workflow_call:  # Called from deploy.yml

# jobs:
#   sync-blog-content:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout portfolio repo
#         uses: actions/checkout@v3

#       - name: Read SDK versions
#         id: sdk
#         run: |
#           BLOG_VERSION=$(jq -r '.blogs.version' scripts/sdk-versions.json)
#           ARTIFACT_PREFIX=$(jq -r '.blogs.artifactPrefix' scripts/sdk-versions.json)
#           REPO=$(jq -r '.blogs.repo' scripts/sdk-versions.json)

#           echo "BLOG_VERSION=$BLOG_VERSION" >> $GITHUB_ENV
#           echo "ARTIFACT_PREFIX=$ARTIFACT_PREFIX" >> $GITHUB_ENV
#           echo "REPO=$REPO" >> $GITHUB_ENV

#           echo "Fetched config: Version=$BLOG_VERSION, Prefix=$ARTIFACT_PREFIX, Repo=$REPO"

#       - name: Fetch latest blog artifact
#         run: |
#           echo "Fetching from repo: $REPO"

#           run_id=$(gh run list -R $REPO \
#             --workflow="Build and Publish Markdown" \
#             --branch=main \
#             --limit=1 \
#             --json databaseId \
#             --jq '.[0].databaseId')

#           echo "Latest Run ID: $run_id"
#           echo "Expecting artifact: ${ARTIFACT_PREFIX}${BLOG_VERSION}"

#           gh run download $run_id \
#             -R $REPO \
#             -n ${ARTIFACT_PREFIX}${BLOG_VERSION} \
#             -D blog-temp

#           echo "Downloaded files in blog-temp:"
#           ls -R blog-temp
#         env:
#           GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

#       - name: Copy blog artifact into public/blogs
#         run: |
#           echo "Cleaning public/blogs..."
#           rm -rf public/blogs/*
#           echo "Copying downloaded blog files..."
#           cp -r blog-temp/* public/blogs/
#           echo "Files in public/blogs after copy:"
#           ls -R public/blogs
