name: Sync Blog and Prepare Build

on:
  push:
    branches:
      - main
    paths:
      - 'package.json'
      - 'scripts/sdk-versions.json'

permissions:
  contents: write  # needed for uploading release asset

jobs:
  sync-blog-and-build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout portfolio repo
      - name: Checkout portfolio repo
        uses: actions/checkout@v3

      # 2. Setup Node.js
      - name: Use Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # 3. Install dependencies
      - name: Install dependencies
        run: npm install

      # 4. Run sync and build script
      - name: Run sync and build script
        run: node scripts/syncBlogAndBuild.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 5. Upload dist as release asset (optional)
      - name: Upload dist to Release
        if: success()
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ env.BLOG_VERSION }}
          name: "Site Build v${{ env.BLOG_VERSION }}"
          files: dist/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
