name: Sync Blog Content

on:
  workflow_call:

jobs:
  sync-blog-content:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout portfolio repo
        uses: actions/checkout@v3

      - name: Read blog config from sdk-versions.json
        id: blog_config
        run: |
          BLOG_VERSION=$(node -p "require('./scripts/sdk-versions.json').blogs.version")
          ARTIFACT_PREFIX=$(node -p "require('./scripts/sdk-versions.json').blogs.artifactPrefix")
          REPO=$(node -p "require('./scripts/sdk-versions.json').blogs.repo")
          echo "BLOG_VERSION=$BLOG_VERSION" >> $GITHUB_ENV
          echo "ARTIFACT_PREFIX=$ARTIFACT_PREFIX" >> $GITHUB_ENV
          echo "REPO=$REPO" >> $GITHUB_ENV

      - name: Fetch latest blog artifact
        run: |
          echo "Fetching from repo: $REPO"
          run_id=$(gh run list -R $REPO --workflow="Build and Publish Markdown" --branch=main --limit=1 --json databaseId --jq '.[0].databaseId')
          echo "Latest Run ID: $run_id"
          echo "Expecting artifact: ${ARTIFACT_PREFIX}${BLOG_VERSION}"
          gh run download $run_id -R $REPO -n ${ARTIFACT_PREFIX}${BLOG_VERSION} -D blog-temp
        env:
          BLOG_VERSION: ${{ env.BLOG_VERSION }}
          ARTIFACT_PREFIX: ${{ env.ARTIFACT_PREFIX }}
          REPO: ${{ env.REPO }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Copy artifact into public/blogs
        run: |
          mkdir -p public/blogs
          cp -r blog-temp/* public/blogs
