name: Sync Blog Content

on:
  workflow_call:

jobs:
  sync-blog-content:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout portfolio repo
        uses: actions/checkout@v3

      - name: Fetch latest blog artifact
        run: |
          run_id=$(gh run list -R Avinashgurugubelli/avi-tech-blogs \
            --workflow="Build and Publish Markdown" \
            --branch=main \
            --limit=1 \
            --json databaseId \
            --jq '.[0].databaseId')

          echo "Latest Run ID: $run_id"

          VERSION=$(node -p "require('./package.json').version")
          echo "Expecting artifact: avi-blogs-v$VERSION"

          gh run download $run_id \
            -R Avinashgurugubelli/avi-tech-blogs \
            -n avi-blogs-v$VERSION \
            -D blog-temp
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Unzip artifact into public/blogs
        run: |
          mkdir -p public/blogs
          unzip blog-temp/blog-out.zip -d public/blogs
